apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
spec:
  # NOTE, if you remove all children from an element, you should remove the
  # element too.  An empty element is interpreted as null and will override all
  # default values (i.e. no values will be specified for that element, not even
  # the defaults baked into the chart values.yaml).
  istio:
    multitenant: false
    launcher:
      enabled: false
    global:
      # force to use rhel7 based proxy-init container
      proxy_init:
        image: proxy-init
      hub: registry.redhat.io/openshift-istio-tech-preview
      tag: 0.11.1
      proxy:
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi

    gateways:
      istio-egressgateway:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
      istio-ingressgateway:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
        # set to true to enable IOR
        ior_enabled: false

    mixer:
      policy:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false

      telemetry:
        # disable autoscaling for use in smaller environments
        autoscaleEnabled: false
        # constrain resources for use in smaller environments
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      # disable autoscaling for use in smaller environments
      autoscaleEnabled: false
      # increase random sampling rate for development/testing
      traceSampling: 100.0
      # constrain resources for use in smaller environments
      resources:
        requests:
          cpu: 500m
          memory: 2G
        limits:
          cpu: 500m
          memory: 3G

    kiali:
      # change to false to disable kiali
      enabled: true
      tag: 0.20.0

    tracing:
      # change to false to disable tracing (i.e. jaeger)
      enabled: true
      hub: distributed-tracing-tech-preview
      tag: 1.11
  threescale:
    enabled: false